name: the_darting_horizon
description: A voyage across the high seas of programming.
version: 1.0.0
repository: https://github.com/brandonp2412/The-Darting-Horizon

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
